### ISSUE TITLE
Browser bar

### ISSUE THREAD

**Issue by jonathanbeaudry** [aldadic/home-assistant-on-echo-show#17]
Can we hide de browser bar?

**Comment by Combatchuck** [comment]
Thats a device setting and for security issue you can't have site forcing full screen, otherwise it would happen on every site you go to

**Comment by aldadic** [comment]
As far as I know, it's not possible, see the discussion here: https://community.home-assistant.io/t/alexa-skill-to-display-lovelace-dashboards-on-echo-show
