### ISSUE TITLE
Feature Request: Usage of "Alexa Web API for Games"

### ISSUE THREAD

**Issue by PepperPhil** [aldadic/home-assistant-on-echo-show#6]
First of all many thanks for this awesome skill! 

This stupid address bar is the only thing, which would be great to get rid of. Since I am a developer myself (unfortunately only for SAP stuff) I was researching a lot to find a solution for that.

However, the only thing I found was the "Alexa Web API for Games"
https://developer.amazon.com/en-US/docs/alexa/web-api-for-games/alexa-games-about.html  

Do you think, we could use this, to display the dashboard (at least for the https Nabu Casa site)?

I wish I would understand this whole skill development better and could help.

Many thanks in advance for checking.

**Comment by aldadic** [comment]
Thanks a lot for sharing! I think the API looks quite promising on the first glance and will definitely try it out. Unfortunately, I am currently very busy and I don't think this will change until Christmas. Hence I am not sure when I'll have a look at this. But I'll keep you updated on my findings!

**Comment by aldadic** [comment]
Hi,

I adapted the skill to use the "Alexa Web API for Games", which was actually fairly easy. Here is the result:

https://gist.github.com/aldadic/4a1fe82fcd0c6207b670d47d3cc453de

The setup is essentially the same: just replace the "lambda_function.py" with the code from above (and adjust the "DASHBOARD_URL" accordingly). The only real difference is that you'll need to also activate the "Alexa Web API for Games" option in the "Interface" menu (just as in step 17):
 
![](https://user-images.githubusercontent.com/88589630/209686122-7884fa98-2978-4f67-9d05-c3f4c95c15a3.png)

Unfortunately, the skill does not work as expected. When I try to open my dashboard, the skill shows the Home Assistant loading screen indefinitely. It also doesn't work when I change the DASHBOARD_URL to "google.com" for example (there I only get a white screen). For static HTML pages on the other hand, the skill works very well. I suspect this has something to do with the [Restrictions of the HTML environment](https://developer.amazon.com/en-US/docs/alexa/web-api-for-games/alexa-games-build-your-webapp.html#restrictions-of-the-html-environment) of the Alexa Web API for Games.

**Comment by PepperPhil** [comment]
Hi,

Maybe we will find a different solution one day.
I hope Amazon will "open" the echo devices a little bit in future. 

Thank you very much for testing it!
